@baseUrl = http://localhost:5000/api

### 1. Login Admin
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "admin@dirasa.com",
  "password": "admin"
}

### Ambil Token dari hasil login di atas
@token = {{login.response.body.token}}

### 2. Lihat Semua Produk
GET {{baseUrl}}/products

### 3. Tambah Produk Baru (Gunakan Token)
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Es Teh Manis",
  "price": 5000,
  "stock": 100,
  "categoryId": "9c771d61-df67-495c-a6fc-737e66847269"
}